################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################

Organizations:
    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
    

    - &admin
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: AdminMSP

        # ID to load the MSP definition as
        ID: AdminMSP

        MSPDir: crypto-config/peerOrganizations/admin.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AdminMSP.admin', 'AdminMSP.peer', 'AdminMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AdminMSP.admin', 'AdminMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AdminMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('AdminMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.admin.coffee-chain.net
              Port: 7051


    - &inspector
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: InspectorMSP

        # ID to load the MSP definition as
        ID: InspectorMSP

        MSPDir: crypto-config/peerOrganizations/inspector.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('InspectorMSP.admin', 'InspectorMSP.peer', 'InspectorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('InspectorMSP.admin', 'InspectorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('InspectorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('InspectorMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.inspector.coffee-chain.net
              Port: 7052
    

    - &harvester
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: HarvesterMSP

        # ID to load the MSP definition as
        ID: HarvesterMSP

        MSPDir: crypto-config/peerOrganizations/harvester.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HarvesterMSP.admin', 'HarvesterMSP.peer', 'HarvesterMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HarvesterMSP.admin', 'HarvesterMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HarvesterMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('HarvesterMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.harvester.coffee-chain.net
              Port: 7053
    

    - &exporter
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ExpoerterMSP

        # ID to load the MSP definition as
        ID: ExpoerterMSP

        MSPDir: crypto-config/peerOrganizations/exporter.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ExpoerterMSP.admin', 'ExpoerterMSP.peer', 'ExpoerterMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ExpoerterMSP.admin', 'ExpoerterMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ExpoerterMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ExpoerterMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.exporter.coffee-chain.net
              Port: 7054

    - &importer
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ImporterMSP

        # ID to load the MSP definition as
        ID: ImporterMSP

        MSPDir: crypto-config/peerOrganizations/importer.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ImporterMSP.admin', 'ImporterMSP.peer', 'ImporterMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ImporterMSP.admin', 'ImporterMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ImporterMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ImporterMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.importer.coffee-chain.net
              Port: 7055

    - &processor
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ProcessorMSP

        # ID to load the MSP definition as
        ID: ProcessorMSP

        MSPDir: crypto-config/peerOrganizations/processor.coffee-chain.net/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('ProcessorMSP.admin', 'ProcessorMSP.peer', 'ProcessorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('ProcessorMSP.admin', 'ProcessorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('ProcessorMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('ProcessorMSP.peer')"

    # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.processor.coffee-chain.net
              Port: 7056


################################################################################
#
#   SECTION: Capabilities
#
#   - This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
    Channel: &ChannelCapabilities
        # V2_0 capability ensures that orderers and peers behave according
        # to v2.0 channel capabilities. Orderers and peers from
        # prior releases would behave in an incompatible way, and are therefore
        # not able to participate in channels at v2.0 capability.
        # Prior to enabling V2.0 channel capabilities, ensure that all
        # orderers and peers on a channel are at v2.0.0 or later.
        V2_0: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
    Orderer: &OrdererCapabilities
        # V2_0 orderer capability ensures that orderers behave according
        # to v2.0 orderer capabilities. Orderers from
        # prior releases would behave in an incompatible way, and are therefore
        # not able to participate in channels at v2.0 orderer capability.
        # Prior to enabling V2.0 orderer capabilities, ensure that all
        # orderers on channel are at v2.0.0 or later.
        V2_0: true

    # Application capabilities apply only to the peer network, and may be safely
    # used with prior release orderers.
    # Set the value of the capability to true to require it.
    Application: &ApplicationCapabilities
        # V2_0 application capability ensures that peers behave according
        # to v2.0 application capabilities. Peers from
        # prior releases would behave in an incompatible way, and are therefore
        # not able to participate in channels at v2.0 application capability.
        # Prior to enabling V2.0 application capabilities, ensure that all
        # peers on channel are at v2.0.0 or later.
        V2_0: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################

Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: orderer.coffee-chain.net
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/coffee-chain.net/orderers/orderer.coffee-chain.net/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/coffee-chain.net/orderers/orderer.coffee-chain.net/tls/server.crt

    Addresses:
        - orderer.coffee-chain.net:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        # Who may invoke the 'Deliver' API
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        # Who may invoke the 'Broadcast' API
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        # By default, who may modify elements at this config level
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
        <<: *ChannelCapabilities


################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################

Profiles:

    BasicChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
               - *admin
               - *inspector
               - *harvester
               - *exporter
               - *importer
               - *processor
            Capabilities:
                <<: *ApplicationCapabilities


    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.coffee-chain.net
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/coffee-chain.net/orderers/orderer.coffee-chain.net/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/coffee-chain.net/orderers/orderer.coffee-chain.net/tls/server.crt
            
            Addresses:
              - orderer.coffee-chain.net:7050
 
            Organizations:
            - *OrdererOrg

            Capabilities:
             <<: *OrdererCapabilities

        Consortiums:
           SampleConsortium:
              Organizations:
               - *admin
               - *inspector
               - *harvester
               - *exporter
               - *importer
               - *processor
              